### ISSUE TITLE
Busted icons on atom.io website

### ISSUE THREAD

**Issue by jaredhirsch** [atom/atom.io#166] opened 2018-09-10 19:03 UTC
Howdy! Noticed some funky-looking icons on the token download page, and it turns out they are visible on the homepage, too.

On https://atom.io, I see this on the far right side of the header:

Firefox:  <img width="107" alt="screen shot 2018-09-10 at 11 59 36 am" src="https://user-images.githubusercontent.com/96396/45318208-0b082000-b4f1-11e8-9d2a-095290559f75.png">

Chrome: <img width="90" alt="screen shot 2018-09-10 at 12 00 22 pm" src="https://user-images.githubusercontent.com/96396/45318230-1d825980-b4f1-11e8-9842-09737e9e80fb.png">

And I see this in the footer:

Firefox: <img width="132" alt="screen shot 2018-09-10 at 12 01 14 pm" src="https://user-images.githubusercontent.com/96396/45318277-3be85500-b4f1-11e8-91d3-fb839bcf2f9a.png">

Chrome: <img width="154" alt="screen shot 2018-09-10 at 12 00 50 pm" src="https://user-images.githubusercontent.com/96396/45318260-2f63fc80-b4f1-11e8-8357-c56bf54b4ccf.png">

**Comment by winstliu** [comment] 2018-09-10 20:19
Confirmed.  @queerviolet this is caused by #164.
![image](https://user-images.githubusercontent.com/2766036/45322098-4288c380-b515-11e8-83ab-4cc6251cc705.png)

**Comment by tambry** [comment] 2018-09-11 05:25
My guess is this was because the CDN URLs were updated only in the HTML and not also in the CSS, and worked initially, because the CSP didn't apply.

**Comment by queerviolet** [comment] 2018-09-11 17:19
Investigated this a bit yesterday and couldn't find where the old CDN url was lurking. Rolled back, will investigate more today.

**Comment by lee-dohm** [comment] 2018-09-11 20:21
Since this is fixed and there is another issue tracking the work, I'm going to close this. Thanks for reporting the problem! :bow:

**Closed as completed by lee-dohm** 2018-09-11 20:21 UTC
Labels: bug
