### ISSUE TITLE
"Getting Started" Section Wrong Links

### ISSUE THREAD

**Issue by abyssvi** [atom/atom.io#54] opened 2016-02-02 16:23 UTC
The Documentation part of the website has gone a bit weird.

If you are on https://atom.io/docs and hit "1. Getting Started" it takes you to https://atom.io/docs/v1.4.1/upgrading-to-1-0-apis-upgrading-your-package

From that page, on the left bar, 1.1, 1.2, and 1.3 are all incorrectly things involving upgrading packages, and not "Getting Started".

The only way to get to the *actual* Getting Started section is to go to the table of contents and click on the sections.

Additionally, it seems like all the links on https://atom.io/docs are taking you to the v1.4.1 docs, which give an error that they're not the latest.

**Comment by 50Wliu** [comment] 2016-02-02 17:06
This is a duplicate of atom/docs#155 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-02-02 17:06 UTC
