### ISSUE TITLE
atom.io incorrectly showing 1.39 available 

### ISSUE THREAD

**Issue by hermidalc** [atom/atom.io#185] opened 2019-07-19 21:16 UTC
*Edit by @rsese: http://atom.io says 1.39.0 is available for download, but the releases you get are for 1.38.*

**Comment by rsese** [comment] 2019-07-20 01:40
Thanks for the heads up @hermidalc - 1.39.0 hasn't been released yet so atom.io is showing the wrong release version details /cc @jasonrudolph

**Comment by jasonrudolph** [comment] 2019-07-20 11:45
Thanks for the heads up. This should be fixed now.

<img width="501" alt="Screen Shot 2019-07-20 at 7 45 00 AM" src="https://user-images.githubusercontent.com/2988/61578288-61a39a80-aac2-11e9-8a4a-4667534bdc06.png">

**Comment by hermidalc** [comment] 2019-07-22 15:06
Tell me I'm crazy... but website it showing 1.39 again yet the downloadable Linux rpm is still 1.38.2
```bash
$ sudo dnf install -y Downloads/atom.x86_64.rpm 
Fedora Modular 30 - x86_64                                                                                            247 kB/s |  18 kB     00:00    
Fedora Modular 30 - x86_64 - Updates                                                                                  184 kB/s |  17 kB     00:00    
Fedora 30 - x86_64 - Updates                                                                                           39 kB/s |  17 kB     00:00    
Fedora 30 - x86_64                                                                                                     47 kB/s |  18 kB     00:00    
Package atom-1.38.2-0.1.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
```

**Comment by Arcanemagus** [comment] 2019-07-22 16:34
As you can see from the [releases page](https://github.com/atom/atom/releases) v1.38.2 is still the current stable build, looks like the website is jumping the gun a bit again 😆.

**Comment by jasonrudolph** [comment] 2019-07-23 14:17
> As you can see from the [releases page](https://github.com/atom/atom/releases) v1.38.2 is still the current stable build, looks like the website is jumping the gun a bit again 😆.

Can you tell that we were excited to ship v1.39.0? 😂 

It's [out for real now](https://github.com/atom/atom/releases/tag/v1.39.0), so atom.io is now telling the truth about the latest version. 😅 With that in mind, I think we can close this issue now.

**Comment by Aerijo** [comment] 2019-08-13 09:18
@jasonrudolph Stable is still 1.39.1

![image](https://user-images.githubusercontent.com/22167388/62930090-0d5cb380-bdff-11e9-8018-55970bba4b60.png)

**Comment by jasonrudolph** [comment] 2019-08-14 16:50
Thanks for reopening this issue, @Aerijo. :bow:

I think I've tracked down the root cause. atom.io receives a [webhook payload for release events](https://developer.github.com/v3/activity/events/types/#releaseevent), but atom.io wasn't distinguishing between a *draft* release and a *published* release. We've rolled out a fix to atom.io to only update the Atom version when a new stable release is _published_. 😅

**Closed as completed by jasonrudolph** 2019-08-14 16:50 UTC
