### ISSUE TITLE
atom won't open from command line or from doc

### ISSUE THREAD

**Issue by justinchristensen66** [atom/atom.io#116] opened 2017-04-18 01:11 UTC
I get this message when I try to open atom from terminal or doc   **'LSOpenURLsWithRole() failed for the application /Users/justinchristensen66/Downloads/Atom.app with error -10810.'**   Everything was fine the other day and now this.  In the message that appears in  alert prompt:  '**Check with the developer to make sure Atom works with this version of macOS. You may need to reinstall the application. Be sure to install any available updates for the application and macOS**.'   Do I have to reinstall, I was reading there are lots of things to clean up when uninstalling?

**Comment by winstliu** [comment] 2017-04-18 01:17
Looks like a duplicate of https://github.com/atom/atom/issues/3093.  Make sure you are not running in tmux.

If you still wish to uninstall, the only thing to remember is that your `~/.atom` directory is persisted and you'll need to delete that separately (but if you do, all your settings and installed packages will be gone).

**Closed as completed by winstliu** 2017-04-18 01:17 UTC
Labels: duplicate, wrong-repo

**Comment by justinchristensen66** [comment] 2017-04-18 01:28
im not running in tmux its in Iterm but it also wont open from the doc. I'm
on a mac 10.12.4  If i have to uninstall, is the ~/.atom directory the only
directory I have to delete?  Thanks so much for your help.

**Comment by winstliu** [comment] 2017-04-18 01:38
That should be the only directory that you need to remove.  I can't think of any others.

**Comment by justinchristensen66** [comment] 2017-04-18 01:46
Is removing it the best course of action?

**Comment by winstliu** [comment] 2017-04-18 01:50
I would temporarily rename it to `~/.atom-backup`.  That way, you don't lose everything and have a backup just in case.
