### ISSUE TITLE
Show Current Version on Homepage

### ISSUE THREAD

**Issue by pertrai1** [atom/atom.io#104] opened 2016-12-20 03:23 UTC
Is it possible to show the latest version right under the Download button so a user will know what version it is that is being downloaded? Think this would be good for a user to know about.

**Comment by mnquintana** [comment] 2016-12-21 19:53
Thanks for the suggestion! This looks like a duplicate of https://github.com/atom/atom.io/issues/104 – closing this out in favor of that issue

**Closed as completed by mnquintana** 2016-12-21 19:53 UTC
Labels: duplicate, enhancement
