### ISSUE TITLE
Atom China Official Website Can't Open Normally

### ISSUE THREAD

**Issue by Ivorzk** [atom/atom.io#186] opened 2019-07-30 09:36 UTC
Atom China Official Website Can't Open Normally
![图片](https://user-images.githubusercontent.com/7390138/62118588-854fb780-b2f0-11e9-9eac-2aaeb2e3d136.png)

**Comment by rsese** [comment] 2019-07-30 19:01
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom.io/issues/177 so you can subscribe there if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed as completed by rsese** 2019-07-30 19:01 UTC
Labels: duplicate
