### ISSUE TITLE
Atom OAuth application is labeled as 'Not owned or operated by GitHub'

### ISSUE THREAD

**Issue by tilda** [atom/atom.io#165] opened 2018-08-23 00:48 UTC
While authenticating with atom.io, I noticed that the app wasn't labeled as owned by GitHub. Shouldn't this one be marked as made by GitHub?

**Comment by lee-dohm** [comment] 2018-08-23 02:40
That's a fair point. I'm not sure what can be done about it right away but it is something that I'll investigate.

## Steps to reproduce

1. Navigate to https://github.com/settings/applications
1. Find `Atom.io` in the list
1. Click the "Revoke" button
1. Click the "I understand, revoke access" button on the dialog that appears
1. Navigate to https://atom.io
1. Click the sign out button (the "exit" or "way out" icon in the top bar)
1. Click "Sign in" in the top bar

At the bottom of the authorization screen, you'll see this:

<img width="637" alt="screen shot 2018-08-22 at 7 34 12 pm" src="https://user-images.githubusercontent.com/1038121/44501656-08797f80-a643-11e8-8f36-be63ee8509a2.png">

**Comment by lee-dohm** [comment] 2018-08-23 16:11
This is a duplicate of #145 and https://github.com/atom/github/issues/1048. Since there is already an issue tracking this for this repo, I'm going to close this one.  As I said above, it isn't something that we have a great solution for right now but it is something that we would like to fix longer-term.

**Closed as completed by lee-dohm** 2018-08-23 16:11 UTC
Labels: duplicate

**Comment by AW1534** [comment] 2022-02-26 17:56
4 years later:
