### ISSUE TITLE
Broken "TextEditorElement" link

### ISSUE THREAD

**Issue by itiut** [atom/atom.io#65] opened 2016-03-31 23:21 UTC
In [TextEditor documentation](https://atom.io/docs/api/v1.6.1/TextEditor) there is a link to TextEditorElement, but it is broken.

**Comment by 50Wliu** [comment] 2016-03-31 23:56
This is a duplicate of atom/flight-manual.atom.io#128 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-03-31 23:56 UTC
