### ISSUE TITLE
"Search in Directory" is missing in Linux

### ISSUE THREAD

**Issue by ardavis** [atom/atom.io#117] opened 2017-05-01 12:34 UTC
In my Red Hat Enterprise Linux 6 installation, there is no "Search in Directory" context menu. I see it on the Mac and Ubuntu though. Any idea what might be going on?

I do not have admin on this machine, I installed it with:

    ./script/build --install=/my/custom/path/to/atom

**Comment by winstliu** [comment] 2017-05-01 15:14
This is the issue repository for the https://atom.io _website_.  If you have a problem with Atom itself, you should be opening it on either atom/atom (if it's a core issue) or atom/\<package-name\> if it is a core package issue.
***
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/find-and-replace/issues/887. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed as completed by winstliu** 2017-05-01 15:14 UTC
Labels: duplicate, wrong-repo
