### ISSUE TITLE
Large files will not show text but I can copy it.

### ISSUE THREAD

**Issue by sandros94** [atom/atom.io#168] opened 2018-09-14 11:16 UTC
Hi, I'm in need to check the ending lines of some large files (600-700MB mostly sql), atom is super quick in opening them but around line 1.5M the text just disappear, if I try to select it and copy-paste somewhere else it lets me do it, but still it doesn't let me see it in the original file. Is this a bug or just atom that is not able to load at gui level all that text? I'm use to do it on Notepad++, but it freezes for 10 minutes before I can look at the code.

UPDATE: For those interested in a example file [here](https://drive.google.com/open?id=1J9QngO12Sl8UYEWFSRgG1qwXONcosS1r) it is.

**Comment by Arcanemagus** [comment] 2018-09-14 19:50
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/16591. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed as completed by Arcanemagus** 2018-09-14 19:50 UTC
Labels: duplicate
