### ISSUE TITLE
README: support "Task Lists"

### ISSUE THREAD

**Issue by jessexknight** [atom/atom.io#160] opened 2018-07-07 00:19 UTC
GitHub README markdown flavour supports a nice syntax for rendering checkbox lists called "[Task Lists](https://help.github.com/articles/basic-writing-and-formatting-syntax/#task-lists)"

Is it possible to support this also for Package Pages? ... since they copy the README from GitHub repo.

Better yet, maybe: is it possible to synchronize GitHub README Markdown flavor with the Package Pages rendering, so they always provide the same features?

**Comment by winstliu** [comment] 2018-07-07 00:22
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #125. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed as completed by winstliu** 2018-07-07 00:22 UTC
Labels: duplicate

**Comment by jessexknight** [comment] 2018-07-07 00:30
Sorry about that! I did try to look for existing duplicates - apparently not very hard...

**Comment by winstliu** [comment] 2018-07-07 02:05
No problem - sometimes it's hard to find a duplicate unless you've seen it before :).
